import jsPDF from "jspdf"
import type { SimulationResult } from "@/lib/types"

export async function exportToPDF(results: SimulationResult, scenario: string, category: string): Promise<boolean> {
  try {
    // Create a new PDF document
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    })

    // Set document properties
    pdf.setProperties({
      title: "Dream Scenario Simulation",
      subject: scenario,
      author: "Dream Scenario Simulator",
      keywords: "simulation, AI, scenario",
      creator: "Dream Scenario Simulator",
    })

    // Helper function to add wrapped text
    const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number) => {
      const lines = pdf.splitTextToSize(text, maxWidth)
      pdf.text(lines, x, y)
      return y + lineHeight * lines.length
    }

    // Add title
    pdf.setFontSize(22)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Dream Scenario Simulation", 105, 20, { align: "center" })

    // Add scenario
    pdf.setFontSize(14)
    pdf.setTextColor(52, 73, 94)
    let y = 30
    y = addWrappedText(scenario, 105, y, 180, 7) + 5

    // Add date
    pdf.setFontSize(10)
    pdf.setTextColor(127, 140, 141)
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 105, y, { align: "center" })
    y += 10

    // Add horizontal line
    pdf.setDrawColor(200, 200, 200)
    pdf.line(20, y, 190, y)
    y += 10

    // Add summary section
    pdf.setFontSize(16)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Summary", 20, y)
    y += 8

    pdf.setFontSize(12)
    pdf.setTextColor(52, 73, 94)
    y = addWrappedText(results.summary, 20, y, 170, 6) + 10

    // Add key metrics section
    pdf.setFontSize(16)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Key Metrics", 20, y)
    y += 8

    pdf.setFontSize(12)
    pdf.setTextColor(52, 73, 94)
    pdf.text(`Feasibility: ${results.feasibility}%`, 20, y)
    y += 6
    pdf.text(`Time to Achieve: ${results.timeToAchieve}`, 20, y)
    y += 6
    y = addWrappedText(`Financial Impact: ${results.financialImpact}`, 20, y, 170, 6) + 10

    // Add advantages section
    pdf.setFontSize(16)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Key Advantages", 20, y)
    y += 8

    pdf.setFontSize(12)
    pdf.setTextColor(52, 73, 94)
    results.advantages.forEach((advantage) => {
      y = addWrappedText(`• ${advantage}`, 20, y, 170, 6) + 5
    })
    y += 5

    // Add challenges section
    pdf.setFontSize(16)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Potential Challenges", 20, y)
    y += 8

    pdf.setFontSize(12)
    pdf.setTextColor(52, 73, 94)
    results.challenges.forEach((challenge) => {
      y = addWrappedText(`• ${challenge}`, 20, y, 170, 6) + 5
    })
    y += 5

    // Check if we need a new page for recommendations
    if (y > 250) {
      pdf.addPage()
      y = 20
    }

    // Add recommendations section
    pdf.setFontSize(16)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Recommendations", 20, y)
    y += 8

    pdf.setFontSize(12)
    pdf.setTextColor(52, 73, 94)
    results.recommendations.forEach((recommendation) => {
      y = addWrappedText(`• ${recommendation}`, 20, y, 170, 6) + 5
    })
    y += 10

    // Add timeline section (on a new page)
    pdf.addPage()
    y = 20

    pdf.setFontSize(18)
    pdf.setTextColor(44, 62, 80)
    pdf.text("Journey Timeline", 105, y, { align: "center" })
    y += 15

    // Add each timeline event
    results.timeline.forEach((event, index) => {
      // Check if we need a new page
      if (y > 250) {
        pdf.addPage()
        y = 20
      }

      pdf.setFontSize(14)
      pdf.setTextColor(44, 62, 80)
      pdf.text(`${index + 1}. ${event.title}`, 20, y)
      y += 6

      pdf.setFontSize(10)
      pdf.setTextColor(127, 140, 141)
      pdf.text(event.timeframe, 20, y)
      y += 6

      pdf.setFontSize(12)
      pdf.setTextColor(52, 73, 94)
      y = addWrappedText(event.description, 20, y, 170, 6) + 5

      if (event.milestones && event.milestones.length > 0) {
        pdf.setFontSize(11)
        pdf.text("Key Milestones:", 25, y)
        y += 5

        pdf.setFontSize(10)
        event.milestones.forEach((milestone) => {
          y = addWrappedText(`• ${milestone}`, 30, y, 160, 5) + 4
        })
      }
      y += 10
    })

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text("Generated by Dream Scenario Simulator • Powered by AI", 105, pdf.internal.pageSize.height - 10, {
        align: "center",
      })
      pdf.text(`Page ${i} of ${pageCount}`, 190, pdf.internal.pageSize.height - 10, { align: "right" })
    }

    // Save the PDF
    pdf.save(`dream-scenario-${category}-${new Date().getTime()}.pdf`)
    return true
  } catch (error) {
    console.error("Error generating PDF:", error)
    return false
  }
}
